name: FlutterBARD
description: A new Flutter application.

dependencies:
  flutter:
    sdk: flutter
  html: ^0.13.2+2
  shared_preferences: ^0.3.3
  tuple: ^1.0.1
  sqflite: ^0.7.1
  cupertino_icons: ^0.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
