name: FlutterBARD
description: A new Flutter application.

dependencies:
  flutter:
    sdk: flutter
  async_loader: ^0.1.1
  firebase_auth: ^0.5.3
  firebase_database: ^0.4.1
  firebase_messaging: ^0.2.1
  html: ^0.13.3
  meta: ^1.1.2
  path_provider: ^0.4.0
  range: ^1.1.1
  tuple: ^1.0.1
  url_launcher: ^3.0.0
  sembast: ^1.7.0

flutter:
  uses-material-design: true
