name: FlutterBARD
description: A new Flutter application.

dependencies:
  flutter:
    sdk: flutter
  android_intent: ^0.1.1
  async_loader: ^0.1.1
  firebase_auth: ^0.5.0
  firebase_database: ^0.4.0
  html: ^0.13.2+2
  path_provider: ^0.3.1
  range: ^1.1.1
  shared_preferences: ^0.3.3
  tuple: ^1.0.1
  sembast: ^1.6.1
  sqflite: ^0.8.2
  cupertino_icons: ^0.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
