name: FlutterBARD
description: A new Flutter application.

dependencies:
  flutter:
    sdk: flutter
  android_intent: ^0.2.0
  async_loader: ^0.1.1
  firebase_auth: ^0.5.2
  firebase_database: ^0.4.1
  html: ^0.13.3
  meta: ^1.1.2
  path_provider: ^0.4.0
  range: ^1.1.1
  shared_preferences: ^0.4.0
  tuple: ^1.0.1
  url_launcher: ^3.0.0
  sembast: ^1.7.0
  sqflite: ^0.8.4
  cupertino_icons: ^0.1.1

flutter:
  uses-material-design: true
